import type { ReactNode } from "react";

import { Badge } from "@/components/ui/badge";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { formatDateTime, humanize } from "@/lib/utils";
import type { Summary } from "@/types/summary";

export interface SummaryPreviewProps {
  summary: Summary;
  actions?: ReactNode;
  className?: string;
}

export function SummaryPreview({
  summary,
  actions,
  className,
}: SummaryPreviewProps) {
  return (
    <Card className={className}>
      <CardHeader className="gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div className="grid gap-2">
          <div className="flex flex-wrap items-center gap-2">
            <CardTitle className="text-xl">{summary.title}</CardTitle>
            <Badge variant="secondary">{humanize(summary.status)}</Badge>
            <Badge variant="glass">{humanize(summary.source)}</Badge>
          </div>
          <CardDescription>
            {summary.type === "visit" ? "Visit summary" : humanize(summary.type)}
            {summary.model ? ` | ${summary.model}` : ""}
          </CardDescription>
        </div>

        {actions ? <div className="shrink-0">{actions}</div> : null}
      </CardHeader>

      <CardContent className="grid gap-4">
        <p className="m-0 whitespace-pre-line text-sm leading-7 text-[color:var(--ui-text)]">
          {summary.content}
        </p>

        {summary.highlights && summary.highlights.length > 0 ? (
          <>
            <Separator />
            <div className="grid gap-2">
              <div className="text-xs uppercase tracking-[0.2em] text-[color:var(--ui-muted)]">
                Highlights
              </div>
              <ul className="m-0 grid gap-2 pl-5 text-sm leading-6 text-[color:var(--ui-muted)]">
                {summary.highlights.map((item) => (
                  <li key={item}>{item}</li>
                ))}
              </ul>
            </div>
          </>
        ) : null}

        {summary.recommendations && summary.recommendations.length > 0 ? (
          <>
            <Separator />
            <div className="grid gap-2">
              <div className="text-xs uppercase tracking-[0.2em] text-[color:var(--ui-muted)]">
                Follow-up
              </div>
              <ul className="m-0 grid gap-2 pl-5 text-sm leading-6 text-[color:var(--ui-muted)]">
                {summary.recommendations.map((item) => (
                  <li key={item}>{item}</li>
                ))}
              </ul>
            </div>
          </>
        ) : null}

        <Separator />

        <div className="flex flex-wrap gap-3 text-sm text-[color:var(--ui-muted)]">
          <span>Generated by {summary.generatedBy ?? "ChroniSync AI"}</span>
          <span>Updated {formatDateTime(summary.updatedAt)}</span>
        </div>
      </CardContent>
    </Card>
  );
}
